openapi: 3.0.0
info:
  title: Subscribe and Save
  version: 0.0.2
  
paths:
  /subscriptions/users/{userId}/products/{asin}:
    put:
      description: This is a put operation
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: asin
          in: path
          required: true
          schema:
            type: string
        - name: quantity
          in: query
          description: Quantity of .....
          schema:
            type: integer
        - name: monthlyFrequency
          in: query
          description: Frequency
          schema:
            type: integer
